# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

gmail_username: 
gmail_password: 

sf_username: 'shomari.e@contextmediainc.com.staging'
sf_password:  
sf_security_token: 'luzvxCLqrFywA4tcq4GwD8w4'
sf_client_id: '3MVG9sLbBxQYwWqsMePpk_o4w.BOkzVhkOH3KFVjKtXwK9QAKCbDkiNjnVdYCyXeCl8dSTxvKzBmp2oNFzCnj'
sf_client_secret: '2025903504565848878'

### Amazon S3 credentials these have been deleted
aws_access_key:         'AKIAIC57GWCNJT5CLW6A'
aws_secret_access_key: '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'

